# generate-csharp.ps1
# Protocol Buffers C# code generator for XRift Avatar Format
#
# Usage: ./generate-csharp.ps1

param(
    [string]$ProtocVersion = "29.3"
)

$ErrorActionPreference = "Stop"

# Paths
$ScriptDir = $PSScriptRoot
$ProtobufDir = Split-Path $ScriptDir -Parent
$DefinitionDir = Join-Path $ProtobufDir "Definition"
$ProtoFile = Join-Path $DefinitionDir "packages\core\proto\model.proto"
$OutputDir = Join-Path (Split-Path $ProtobufDir -Parent) "Generated"
$ToolsDir = $ScriptDir
$ProtocDir = Join-Path $ToolsDir "protoc-$ProtocVersion"
$ProtocExe = Join-Path $ProtocDir "bin\protoc.exe"

# Namespace for generated code (determined by proto package: avatar_renderer -> AvatarRenderer)
$CSharpNamespace = "AvatarRenderer"

function Write-Status {
    param([string]$Message)
    Write-Host "[generate-csharp] $Message" -ForegroundColor Cyan
}

function Write-Error-Message {
    param([string]$Message)
    Write-Host "[generate-csharp] ERROR: $Message" -ForegroundColor Red
}

function Get-Protoc {
    if (Test-Path $ProtocExe) {
        Write-Status "protoc already exists at $ProtocExe"
        return $true
    }

    Write-Status "Downloading protoc v$ProtocVersion..."

    $ZipUrl = "https://github.com/protocolbuffers/protobuf/releases/download/v$ProtocVersion/protoc-$ProtocVersion-win64.zip"
    $ZipPath = Join-Path $ToolsDir "protoc.zip"

    try {
        # Download
        Write-Status "Downloading from $ZipUrl"
        Invoke-WebRequest -Uri $ZipUrl -OutFile $ZipPath -UseBasicParsing

        # Extract
        Write-Status "Extracting to $ProtocDir"
        Expand-Archive -Path $ZipPath -DestinationPath $ProtocDir -Force

        # Cleanup
        Remove-Item $ZipPath -Force

        if (Test-Path $ProtocExe) {
            Write-Status "protoc downloaded successfully"
            return $true
        } else {
            Write-Error-Message "protoc.exe not found after extraction"
            return $false
        }
    }
    catch {
        Write-Error-Message "Failed to download protoc: $_"
        if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }
        return $false
    }
}

function Generate-CSharp {
    Write-Status "Generating C# code from $ProtoFile"

    # Verify proto file exists
    if (-not (Test-Path $ProtoFile)) {
        Write-Error-Message "Proto file not found: $ProtoFile"
        return $false
    }

    # Create output directory
    if (-not (Test-Path $OutputDir)) {
        New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    }

    # Proto include path
    $ProtoInclude = Join-Path $DefinitionDir "packages\core\proto"

    # Run protoc
    # Note: The namespace is determined by the proto package (avatar_renderer -> AvatarRenderer)
    $ProtocArgs = @(
        "--csharp_out=$OutputDir",
        "--proto_path=$ProtoInclude",
        $ProtoFile
    )

    Write-Status "Running: protoc $($ProtocArgs -join ' ')"

    try {
        & $ProtocExe @ProtocArgs

        if ($LASTEXITCODE -ne 0) {
            Write-Error-Message "protoc failed with exit code $LASTEXITCODE"
            return $false
        }

        # Check output
        $GeneratedFile = Join-Path $OutputDir "Model.cs"
        if (Test-Path $GeneratedFile) {
            Write-Status "Generated: $GeneratedFile"

            # Add namespace wrapper comment for clarity
            $Content = Get-Content $GeneratedFile -Raw
            $Header = "// <auto-generated>
//     Generated by protoc v$ProtocVersion from model.proto
//     DO NOT EDIT - changes will be overwritten
// </auto-generated>
"
            if (-not $Content.StartsWith("// <auto-generated>")) {
                $Content = $Header + $Content
                Set-Content -Path $GeneratedFile -Value $Content -NoNewline
                Write-Status "Added auto-generated header"
            }

            return $true
        } else {
            Write-Error-Message "Expected output file not found: $GeneratedFile"
            return $false
        }
    }
    catch {
        Write-Error-Message "Failed to run protoc: $_"
        return $false
    }
}

# Main
Write-Status "=== XRift Avatar Format C# Code Generator ==="
Write-Status "Proto file: $ProtoFile"
Write-Status "Output dir: $OutputDir"
Write-Status "Namespace:  $CSharpNamespace"
Write-Status ""

# Step 1: Ensure protoc is available
if (-not (Get-Protoc)) {
    exit 1
}

# Step 2: Generate C# code
if (-not (Generate-CSharp)) {
    exit 1
}

Write-Status ""
Write-Status "=== Generation complete ==="
